baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Burntcow MediaWorks"


# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  companyName = "Burntcow MediaWorks"

[permalinks]
  posts = "/blog/:title"

[menu]
  [[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work/"

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"

  [[menu.main]]
    identifier = "team"
    name = "Team"
    url = "/team/"

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
